services:
  server:
    image: redash/redash:25.1.0
    platform: linux/amd64
    command: server
    depends_on:
      - postgres
      - redis
    ports:
      - "5001:5000"
    environment:
      REDASH_LOG_LEVEL: ${REDASH_LOG_LEVEL}
      REDASH_COOKIE_DOMAIN: ${REDASH_COOKIE_DOMAIN}
      REDASH_PUBLIC_URL: ${REDASH_PUBLIC_URL}
      REDASH_HOST: ${REDASH_HOST}
      REDASH_DATABASE_URL: ${REDASH_DATABASE_URL}
      REDASH_REDIS_URL: ${REDASH_REDIS_URL}
      REDASH_COOKIE_SECRET: ${REDASH_COOKIE_SECRET}
      REDASH_SECRET_KEY: ${REDASH_SECRET_KEY}
      REDASH_ENFORCE_CSRF: ${REDASH_ENFORCE_CSRF}
      REDASH_ENFORCE_HTTPS: ${REDASH_ENFORCE_HTTPS}
    volumes:
      - ./data:/app/data

  scheduler:
    image: redash/redash:25.1.0
    platform: linux/amd64
    command: scheduler
    depends_on:
      - server
      - postgres
      - redis
    environment:
      REDASH_LOG_LEVEL: ${REDASH_LOG_LEVEL}
      REDASH_COOKIE_DOMAIN: ${REDASH_COOKIE_DOMAIN}
      REDASH_PUBLIC_URL: ${REDASH_PUBLIC_URL}
      REDASH_HOST: ${REDASH_HOST}
      REDASH_DATABASE_URL: ${REDASH_DATABASE_URL}
      REDASH_REDIS_URL: ${REDASH_REDIS_URL}
      REDASH_COOKIE_SECRET: ${REDASH_COOKIE_SECRET}
      REDASH_SECRET_KEY: ${REDASH_SECRET_KEY}
      REDASH_ENFORCE_CSRF: ${REDASH_ENFORCE_CSRF}
      REDASH_ENFORCE_HTTPS: ${REDASH_ENFORCE_HTTPS}
    volumes:
      - ./data:/app/data

  worker:
    image: redash/redash:25.1.0
    platform: linux/amd64
    command: worker
    depends_on:
      - server
      - postgres
      - redis
    environment:
      REDASH_LOG_LEVEL: ${REDASH_LOG_LEVEL}
      REDASH_COOKIE_DOMAIN: ${REDASH_COOKIE_DOMAIN}
      REDASH_PUBLIC_URL: ${REDASH_PUBLIC_URL}
      REDASH_HOST: ${REDASH_HOST}
      REDASH_DATABASE_URL: ${REDASH_DATABASE_URL}
      REDASH_REDIS_URL: ${REDASH_REDIS_URL}
      REDASH_COOKIE_SECRET: ${REDASH_COOKIE_SECRET}
      REDASH_SECRET_KEY: ${REDASH_SECRET_KEY}
      REDASH_ENFORCE_CSRF: ${REDASH_ENFORCE_CSRF}
      REDASH_ENFORCE_HTTPS: ${REDASH_ENFORCE_HTTPS}
    volumes:
      - ./data:/app/data

  redis:
    image: redis:6.2-alpine
    volumes:
      - ./redis-data:/data

  postgres:
    image: postgres:13-alpine
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
